# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "light_only" # Currently available options are "default", "air", "light_only"
title                    : "Summary of Lu Kangkai's Personal Experience"
title_separator          : "-"
name                     : &name "LuKangkai"
description              : &description "computational ethnographer<br/>ethnographer of computation"
url                      : "https://Lu-Kangkai.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "staeiou/staeiou.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "kk.png"
  name             : "LuKangkai"
  pronouns         : # example: "she/her"  
  bio              : "As a sophomore at Zhoukou Normal University, Lu Kangkai has achieved outstanding performance in competitions, practical activities and academic studies, with strong comprehensive abilities."
  location         : "San Diego, CA"
  employer         : "UC San Diego"
  uri              : # URL
  email            : # "none@example.org" 

